name: authentication
description: Dart package which manages the authentication domain.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #flutter
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_sign_in: ^5.3.1
  flutterfire_ui: ^0.4.1
  lottie: ^1.4.3
  intl: ^0.18.0
  
  ui:
    git:
      url: https://github.com/flutterrepositories/ui.git
      ref: main # branch name

  #utils
  equatable: ^2.0.0
  meta: ^1.1.8

